# Generated by Django 5.2.3 on 2025-07-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_company_logo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='featured_until',
        ),
        migrations.AddField(
            model_name='job',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When this job ad expires and is no longer visible', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Whether this job is featured'),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('live', 'Live'), ('in_review', 'In Review')], default='in_review', help_text='Current status of the job posting', max_length=20),
        ),
    ]
