# Generated by Django 5.2.3 on 2025-07-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_job_featured_until_job_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='application_contact',
            field=models.CharField(default='', help_text='Email or URL for job applications', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, help_text='SEO-friendly URL slug', max_length=255, null=True, unique=True),
        ),
    ]
