# Generated by Django 5.2.3 on 2025-07-07 17:15

from django.db import migrations


def clear_existing_jobs(apps, schema_editor):
    """Clear existing jobs with numeric IDs since we're converting to UUIDs"""
    Job = apps.get_model('jobs', 'Job')
    Job.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_id'),
    ]

    operations = [
        migrations.RunPython(clear_existing_jobs),
    ]
