# Generated by Django 5.2.3 on 2025-08-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20250707_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(blank=True, help_text='SEO-friendly URL slug', max_length=255, null=True, unique=True),
        ),
    ]
