# Generated by Django 5.2.3 on 2025-08-31 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_company_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Payment amount in EUR', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Payment transaction reference', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Payment Pending'), ('verified', 'Payment Verified'), ('failed', 'Payment Failed'), ('refunded', 'Refunded')], default='pending', help_text='Current payment status', max_length=20),
        ),
    ]
