# Generated by Django 5.2.3 on 2025-08-31 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_job_payment_amount_job_payment_reference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSubmissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.TextField(blank=True)),
                ('result', models.CharField(choices=[('success', 'Success'), ('validation_error', 'Validation Error'), ('system_error', 'System Error'), ('rate_limited', 'Rate Limited'), ('spam_detected', 'Spam Detected')], max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('job_title', models.CharField(blank=True, max_length=200)),
                ('error_details', models.TextField(blank=True)),
                ('form_data_hash', models.CharField(blank=True, max_length=64)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['ip_address', 'submitted_at'], name='jobs_jobsub_ip_addr_2288ce_idx'), models.Index(fields=['result', 'submitted_at'], name='jobs_jobsub_result_5c45c3_idx')],
            },
        ),
    ]
