# Generated by Django 5.2.3 on 2025-10-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_jobsubmissionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('live', 'Live'), ('approved', 'Approved'), ('in_review', 'In Review')], default='in_review', help_text='Current status of the job posting', max_length=20),
        ),
    ]
