# Generated by Django 5.2.3 on 2025-10-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_job_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='job',
            name='payment_reference',
        ),
        migrations.RemoveField(
            model_name='job',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('in_review', 'In Review'), ('rejected', 'Rejected'), ('waiting_for_payment', 'Waiting for Payment'), ('refunded', 'Refunded'), ('live', 'Live')], default='in_review', help_text='Current status of the job posting', max_length=20),
        ),
    ]
