# Generated by Django 5.2.3 on 2025-11-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_remove_job_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='website_url',
            field=models.URLField(blank=True, help_text='Company website URL', null=True),
        ),
    ]
