# Generated by Django 5.2.3 on 2025-12-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_company_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('job', 'Job'), ('cofounder', 'Co-founder')], default='job', help_text='Type of posting: regular job or co-founder search', max_length=20),
        ),
    ]
