# Generated by Django 5.2.3 on 2026-01-27 07:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_job_job_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HireMePost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this post expires and is no longer visible', null=True)),
                ('status', models.CharField(choices=[('in_review', 'In Review'), ('rejected', 'Rejected'), ('live', 'Live'), ('expired', 'Expired')], default='in_review', help_text='Current status of the post', max_length=20)),
                ('title', models.CharField(help_text="Short title for the post (e.g., 'Senior React Developer Available')", max_length=200)),
                ('description', models.TextField(help_text="Detailed description of skills, experience, and what you're looking for")),
                ('contact_info', models.CharField(help_text='Email or other contact information', max_length=255)),
                ('name', models.CharField(help_text='Your name (optional)', max_length=100)),
                ('location', models.CharField(blank=True, help_text='Your location (optional)', max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='SEO-friendly URL slug', max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Hire Me Post',
                'verbose_name_plural': 'Hire Me Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HireMeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Tag name (e.g., 'React', 'Marketing')", max_length=50, unique=True)),
                ('slug', models.SlugField(help_text='SEO-friendly URL slug', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HireMePostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='jobs.hiremepost')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='jobs.hiremetag')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('post', 'tag')},
            },
        ),
    ]
