# Generated by Django 5.2.3 on 2026-03-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0014_hiremepost_hiremetag_hiremeposttag"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="description",
            field=models.TextField(
                blank=True, help_text="Short company description for SEO meta tags"
            ),
        ),
    ]
