services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=False
      - STATIC_ROOT=/app/staticfiles
      - DATABASE_PATH=/app/data/db.sqlite3
    volumes:
      - ${DB_DIR:-.}/db.sqlite3:/app/data/db.sqlite3
      - logs:/app/logs
      - static_files:/app/staticfiles
    restart: unless-stopped

volumes:
  logs:
  static_files:
