[project]
name = "tallinnstartups"
version = "0.1.0"
description = "Django project for Tallinn startups"
authors = [
    {name = "artjom"}
]
readme = "README.md"
requires-python = "^3.12"
dependencies = [
    "django (>=5.2.3,<6.0.0)",
    "faker (>=37.4.0,<38.0.0)",
    "django-ratelimit (>=4.1.0,<5.0.0)",
    "bleach (>=6.1.0,<7.0.0)",
    "django-recaptcha (>=4.0.0,<5.0.0)",
    "requests (>=2.25.0,<3.0.0)",
    "markdown (>=3.10,<4.0)",
    "djangorestframework (>=3.16.1,<4.0.0)",
    "djangorestframework-simplejwt (>=5.5.1,<6.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
