[project]
name = "tallinnstartups"
version = "0.1.0"
description = "Django project for Tallinn startups"
authors = [
    {name = "artjom"}
]
readme = "README.md"
requires-python = "^3.12"
dependencies = [
    "django (>=5.2.3,<6.0.0)",
    "faker (>=37.4.0,<38.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
