from django.core.management.base import BaseCommand
from django.utils import timezone
from faker import Faker
import random
from datetime import timedelta
from blog.models import BlogArticle, BlogCategory # Corrected model imports

class Command(BaseCommand):
    help = 'Generate fake articles for the blog app'

    def add_arguments(self, parser):
        parser.add_argument(
            '--articles',
            type=int,
            default=15,
            help='Number of articles to create (default: 15)'
        )
        parser.add_argument(
            '--clear',
            action='store_true',
            help='Clear existing articles before generating new data'
        )

    def handle(self, *args, **options):
        fake = Faker()

        if options['clear']:
            self.stdout.write(self.style.WARNING('Clearing existing articles...'))
            BlogArticle.objects.all().delete() # Corrected
            BlogCategory.objects.all().delete() # Corrected
            self.stdout.write(self.style.SUCCESS('Existing articles cleared.'))

        # Ensure some categories exist for articles
        if not BlogCategory.objects.exists(): # Corrected
            self.stdout.write(self.style.WARNING('No categories found. Generating default categories...'))
            default_categories = ['Startup Life', 'Funding', 'Tech Trends', 'Marketing', 'Product Management', 'Ecosystem']
            for cat_name in default_categories:
                BlogCategory.objects.create(name=cat_name) # Slug is auto-generated by model save method
            self.stdout.write(self.style.SUCCESS(f'Created {len(default_categories)} default categories.'))

        categories = list(BlogCategory.objects.all()) # Corrected
        if not categories:
            self.stdout.write(self.style.ERROR('No categories available to assign to articles. Please create some categories first.'))
            return

        self.stdout.write(f'Generating {options["articles"]} articles...')
        articles = self.generate_articles(fake, categories, options['articles'])
        self.stdout.write(self.style.SUCCESS(f'Created {len(articles)} articles.'))

        self.stdout.write(self.style.SUCCESS('Fake article generation completed!'))

    def generate_articles(self, fake, categories, count):
        articles = []
        for _ in range(count):
            title = fake.sentence(nb_words=random.randint(5, 12)).replace('.', '')
            # Slug will be generated by the model's save method
            
            excerpt = fake.paragraph(nb_sentences=2) # Added excerpt field

            content = ""
            for _ in range(random.randint(5, 15)): # 5 to 15 paragraphs
                content += f"<p>{fake.paragraph(nb_sentences=random.randint(3, 8))}</p>"
            content += f"<h2>{fake.sentence(nb_words=random.randint(4, 8))}</h2>"
            for _ in range(random.randint(3, 7)): # 3 to 7 paragraphs
                content += f"<p>{fake.paragraph(nb_sentences=random.randint(2, 6))}</p>"
            content += f"<h3>{fake.sentence(nb_words=random.randint(3, 6))}</h3>"
            for _ in range(random.randint(2, 5)): # 2 to 5 paragraphs
                content += f"<p>{fake.paragraph(nb_sentences=random.randint(2, 5))}</p>"
            
            category = random.choice(categories)
            
            published_days_ago = random.randint(0, 365) # Published within the last year
            published_at = timezone.now() - timedelta(days=published_days_ago) # Changed to published_at

            article = BlogArticle.objects.create( # Corrected model name
                title=title,
                excerpt=excerpt, # Added excerpt
                content=content,
                category=category,
                status='published', # Changed to status field
                published_at=published_at, # Changed to published_at
                
                # Added SEO fields
                meta_description=fake.paragraph(nb_sentences=2),
                meta_keywords=', '.join(fake.words(nb=5)),
                
                # Added featured image fields
                featured_image=fake.image_url(),
                featured_image_alt=fake.sentence(nb_words=5),
            )
            articles.append(article)
        return articles