# Generated by Django 5.2.3 on 2025-12-30 14:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='SEO-friendly URL slug', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description')),
            ],
            options={
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Article title', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='SEO-friendly URL slug', max_length=255, null=True, unique=True)),
                ('excerpt', models.TextField(help_text='Short description for blog list')),
                ('content', models.TextField(help_text='Main article content (Markdown format)')),
                ('meta_description', models.TextField(blank=True, help_text='Meta description for SEO')),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published')], default='draft', help_text='Article status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='When article was/will be published', null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='When article should be published (future date)', null=True)),
                ('featured_image', models.URLField(blank=True, help_text='URL to featured image', null=True)),
                ('featured_image_alt', models.CharField(blank=True, help_text='Alt text for featured image', max_length=200)),
                ('category', models.ForeignKey(blank=True, help_text='Article category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='blog.blogcategory')),
            ],
            options={
                'verbose_name': 'Blog Article',
                'verbose_name_plural': 'Blog Articles',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status'], name='blog_blogar_status_32c06c_idx'), models.Index(fields=['published_at'], name='blog_blogar_publish_461167_idx'), models.Index(fields=['category'], name='blog_blogar_categor_5adcc5_idx'), models.Index(fields=['slug'], name='blog_blogar_slug_f79c8c_idx')],
            },
        ),
    ]
